// LeetCode Stats Service - Reads from pre-fetched JSON data
// Data is updated daily via GitHub Actions

export async function fetchLeetCodeData(username) {
  try {
    // Try to fetch from the static JSON file generated by GitHub Actions
    const response = await fetch(`${process.env.PUBLIC_URL || ''}/leetcode-stats.json`);
    
    if (!response.ok) {
      throw new Error('Stats file not found');
    }
    
    const data = await response.json();
    
    // Parse submission calendar for monthly progress
    const calendarJson = data.submissionCalendar || '{}';
    const calendar = typeof calendarJson === 'string' ? JSON.parse(calendarJson) : calendarJson;
    
    const submissions = data.recentSubmissions.map(sub => ({
      timestamp: sub.timestamp,
      difficulty: sub.difficulty,
      title: sub.title,
      lang: sub.lang,
      statusDisplay: sub.statusDisplay
    }));

    return {
      profile: data.profile,
      contestInfo: data.contestInfo,
      problemStats: data.problemStats,
      badges: data.badges,
      recentSubmissions: data.recentSubmissions,
      submissions: submissions,
      lastUpdated: data.lastUpdated
    };
    
  } catch (error) {
    console.error('Error loading stats:', error);
    // Return fallback/mock data if fetch fails
    return generateMockData(username);
  }
}

// Mock data generator for testing/development
function generateMockData(username) {
  const now = Math.floor(Date.now() / 1000);
  const day = 86400;

  const submissions = [];
  for (let i = 0; i < 30; i++) {
    if (Math.random() > 0.5) {
      const timestamp = now - (i * day) - Math.floor(Math.random() * 86400);
      submissions.push({
        timestamp,
        difficulty: Math.random() > 0.3 ? (Math.random() > 0.5 ? 'Medium' : 'Hard') : 'Easy',
        title: `Problem ${i + 1}`,
      });
    }
  }

  return {
    profile: {
      username: username || 'krisha-cmd',
      realName: 'Krisha Rajinder Aggarwal',
      avatar: null,
      ranking: 1564049,
      reputation: 0,
      contributionPoints: 0,
    },
    contestInfo: {
      attended: 0,
      rating: 0,
      globalRanking: 0,
      topPercentage: 0,
    },
    problemStats: {
      easy: { solved: 5, total: 850 },
      medium: { solved: 2, total: 1800 },
      hard: { solved: 0, total: 750 },
    },
    badges: [],
    recentSubmissions: [
      { title: 'Two Sum', difficulty: 'Easy', timestamp: now - 3600, lang: 'python3', statusDisplay: 'Accepted' },
      { title: 'Add Two Numbers', difficulty: 'Medium', timestamp: now - day, lang: 'python3', statusDisplay: 'Accepted' },
    ],
    submissions,
    lastUpdated: new Date().toISOString()
  };
}

export default fetchLeetCodeData;
